# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d97dd83f0addc79572d870fd9881c37773dd868043adf087278f84ac0165076ecb42593bddb8e8837eca0f1c5fe9b8550136b6aa54d4d96eb03998224e92c5a

test:
  secret_key_base: 836893b332d9f877e75a0cfca47be969bf22c7094231adaf90a4831eb37402c9b498db4c7fa5a5bfdb3f4e2d22d43774f125c68e53392c908f0423cc3a883855

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
